### ISSUE TITLE
Set homepage in pyproject.toml

### ISSUE THREAD

**Issue by JakobDev** [pypa/packaging-problems#606]
### Problem description

How can I set a Homepage in a pyproject.toml? The [guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata) shows this:
```toml
[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
```
But this is just recognized as a normal URL field by PyPI and not as the homepage as the `url` argument from the old setup.py.

**Comment by henryiii** [comment]
See https://peps.python.org/pep-0621/#have-a-separate-url-home-page-field

It was considered redundant and isn’t included. Some backends try to fill it from the urls if there’s a matching name (setuptools 61+ does, I think). I think others just ignore it entirely as no longer needed.

**Comment by mara004** [comment]
The thing is, then no homepage is shown by pip:

```toml
[project.urls]
homepage = "https://github.com/pypdfium2-team/pypdfium2"  # FIXME not shown by pip
documentation = "https://pypdfium2.readthedocs.io/"
changelog = "https://pypdfium2.readthedocs.io/en/stable/changelog.html"
```

```
$ python3 -m pip show pypdfium2
Name: pypdfium2
Version: 4.0.0b1
Summary: Python bindings to PDFium
Home-page: 
Author: pypdfium2-team
Author-email: geisserml <geisserml@gmail.com>
License: Apache-2.0 or BSD-3-Clause
Location: /home/me/.local/lib/python3.11/site-packages
Editable project location: /home/me/projects/pypdfium2
Requires: 
Required-by: 
```
