### ISSUE TITLE
adding DataFiles to wheel with build and pyproject.toml

### ISSUE THREAD

**Issue by MatthewRalston** [pypa/packaging-problems#637]
### OS version

Arch 6.0.12

### Python version

3.10.1

### Pip version

22.3.1

### Guide link

https://setuptools.pypa.io/en/latest/userguide/datafiles.html

### Problem description

Switching from legacy `setup.py` to `pyproject.toml` has changed my ability to add plain text files along with my codebase.

For example, in the past with `setup.py`:
```python
setup(
...
        package_data={'kmerdb': ['CITATION.txt']},
)
```

with `pyproject.toml`, I cannot discover my citation plaintext file with `python -m build` on pyproject.toml

```toml

[tool.setuptools]
include-package-data = true
packages = ['kmerdb']

[tool.setuptools.package-data]
citation = ["CITATION.txt"]

```
