### ISSUE TITLE
`python -m build` with active virtualenv fails

### ISSUE THREAD

**Issue by victorgveloso** [pypa/packaging-problems#717]
### Summary

My build doesn't work with active virtualenv but works using system-wide python packages.

Tested in two different machines:

1. 
    - OS: Arch Linux
    - Kernel: Linux 6.6.7-arch1-1 x86_64
    - Package versions: 
        - python-3.11.6-1  
        - python-build-1.0.3-1  
        - python-pip-23.3.2-1  
        - python-setuptools-1:69.0.3-1  
        - python-virtualenv-20.25.0-1  
        - python-wheel-0.42.0-1
2.
    - OS: Mac OS Sonoma (14.1)
    - Kernel: Darwin 23.1.0 arm64
    - Package versions:
        - python-3.11.7
        - build-1.0.3
        - pip-23.3.2
        - setuptools-69.0.3
        - virtualenv-20.25.0
        - wheel-0.42.0
### pyproject.toml
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "RMinerLogProcessor"
dependencies = [
    'sortedcontainers==2.4.0',
    'mypy==1.8.0',
    'SQLAlchemy==2.0.25'
]
version = "0.1.1"
authors = [
    { name="Victor Guerra Veloso", email="victorgvbh@gmail.com" },
]
description = "A RMinerLog Processor to generate issues"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/victorgveloso/RMinerLogProcessor"
Issues = "https://github.com/victorgveloso/RMinerLogProcessor/issues"

```

### output.log
https://gist.github.com/victorgveloso/7d7ba1edfac5c7f514c6f8585a388fde

### Steps to reproduce

(In Arch)

1. `# pacman -S python python-build python-setuptools python-wheel python-virtualenv python-pip`
2. `$ python -m build` **passes**
(or)
2. `$ python -m venv venv`
3. `$ source venv/bin/activate`
4. `(venv) $ pip install build setuptools wheel virtualenv pip`
5. `(venv) $ python -m build` **fails**

(In Mac)

1. `# brew install python`
2. `$ pip install -U build setuptools wheel virtualenv pip`
3. `$ python -m build` **passes**
(or)
2. `$ python -m venv venv`
4. `$ source venv/bin/activate`
5. `(venv) $ pip install -U build setuptools wheel virtualenv pip`
6. `(venv) $ python -m build` **fails**
