### ISSUE TITLE
build strips trailing zero in version

### ISSUE THREAD

**Issue by mxjeff** [pypa/packaging-problems#750]
### Problem description

Building a release for a version with trailing zeros, ie. x.x.0 or x.0.0 will strip zero in source distribution but not in wheel.

For instance:
```toml
[project]
name = "mymodule"
version = "1.0.0"

[build-system]
requires = ["setuptools>=61.0.0"]
```
will build `mymodule-1.tar.gz` and `mymodule-1.0.0-py3-none-any.whl`.

I'm pretty sure it previously kept last zeros, [here is a build (cf. l168)](https://gitlab.com/kaliko/python-musicpd/-/jobs/6615280529) where it builds as expected.

Am I missing something?
