### ISSUE TITLE
429 - too many projects

### ISSUE THREAD

**Issue by debuggerone** [pypa/packaging-problems#901]
### Problem description

I am building an abstract package with interfaces for stuff like storage, cache, etc

Want to use that in my quicpro package so I can for example just accept a "storage" instead of a hardcoded solution for S3 or minio or local storage.

So I made 122 repos for the individual drivers for stuff like S3, minio, ... and wanted to reserve the pypi project names to have some sort of consistency before I implement the interfaces (got the interfaces for the different categories already).

How can I get rid of the 429 error?

**Comment by debuggerone** [comment]
```python
    def load_storage_backend(self) -> Optional[StorageInterface]:
        """ Dynamically loads the storage backend from the config. """
        storage_config = self.config["storage"]
        class_path = storage_config["backend"]
        init_args = storage_config.get("init_args", {})

        try:
            module_name, class_name = class_path.rsplit(".", 1)
            module = importlib.import_module(module_name)
            storage_class: Type[StorageInterface] = getattr(module, class_name)

            if not issubclass(storage_class, StorageInterface):
                raise TypeError(f"{class_path} does not implement StorageInterface")

            return storage_class(**init_args)

        except (ImportError, AttributeError, TypeError) as e:
            logger.error("Failed to load storage backend: %s", e)
            return None
```


and then in a config file I could do stuff like this:


```yaml
storage:
  backend: "core-storage-azure_blob.AzureBlobStorage"
  init_args:
    bucket_name: "my-session-tickets"
```

and change it to 


```yaml
storage:
  backend: "core-storage-s3.S3Storage"
  init_args:
    bucket_name: "my-session-tickets"
```

I thought that's a pretty solid approach for handling Vendor Lock-ins
